"""Seed the real DDS catalog into the live gallery demo.

The demo runs in kiosk mode -- no volumes, no promoted production database, and
everything discarded between visitors -- so whatever it shows has to be inserted
from code at startup. `catalog_bootstrap.seed_minimal_catalog` covers that for
CI and E2E, where a small hand-written fixture with known course numbers is
exactly what the tests assert against.

That fixture is the wrong thing to show a visitor: five courses behind a poster
advertising the real Technion catalog. This module seeds the DDS half of the
real one instead -- the three DDS tracks with their actual credit buckets,
semester matrices and course pools, and the courses those tracks name.

The fixture is generated by `scripts/build_demo_seed.py` from files already in
the repo; regenerate it when the DDS export or the raw semester JSON changes.
"""

from __future__ import annotations

import json
import logging
from functools import lru_cache
from pathlib import Path
from typing import Any

from motor.motor_asyncio import AsyncIOMotorDatabase

from app.config import Settings

logger = logging.getLogger(__name__)

DEMO_SEED_FILE = Path(__file__).parent / "seed_data" / "dds_demo_catalog.json"

# Insertion order matters only for readability of the log line; each collection
# is independent. The names double as the `<name>_collection` settings lookup.
DEMO_SEED_COLLECTIONS = (
    "catalog_faculties",
    "catalog_path_options",
    "degree_programs",
    "degree_requirements",
    "catalog_rules",
    "courses",
    "course_offerings",
)


@lru_cache(maxsize=1)
def load_demo_catalog() -> dict[str, list[dict[str, Any]]]:
    """Read the generated fixture. Cached -- it never changes at runtime."""
    if not DEMO_SEED_FILE.is_file():
        raise FileNotFoundError(
            f"demo catalog fixture is missing: {DEMO_SEED_FILE}. "
            "Regenerate it with `python3 scripts/build_demo_seed.py`."
        )
    return json.loads(DEMO_SEED_FILE.read_text(encoding="utf-8"))


async def seed_dds_demo_catalog(
    database: AsyncIOMotorDatabase,
    settings: Settings,
) -> dict[str, int]:
    """Insert the demo catalog, skipping any collection that already has rows.

    Returns the number of documents each collection holds afterwards, so the
    caller can log what a visitor will actually see.
    """
    payload = load_demo_catalog()
    counts: dict[str, int] = {}

    for name in DEMO_SEED_COLLECTIONS:
        documents = payload.get(name) or []
        collection = database[getattr(settings, f"{name}_collection")]

        existing = await collection.count_documents({})
        if existing:
            # A restart against a database that somehow survived, or a second
            # worker racing the first: never double-insert the catalog.
            counts[name] = existing
            continue

        if documents:
            await collection.insert_many(documents)
        counts[name] = len(documents)

    logger.info(
        "Seeded DDS demo catalog: %s",
        ", ".join(f"{name}={counts[name]}" for name in DEMO_SEED_COLLECTIONS),
    )
    return counts
